# Generated by Django 6.0.5 on 2026-06-19 04:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_galleryphoto_review'),
        ('services', '0002_service_is_addon'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryphoto',
            name='service',
            field=models.ForeignKey(blank=True, help_text='Optional — link to a service to show a "Book This Style" button', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gallery_photos', to='services.service'),
        ),
    ]
