# Generated by Django 6.0.5 on 2026-06-11 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='is_addon',
            field=models.BooleanField(default=False, help_text='Add-on only — not bookable as a standalone appointment'),
        ),
    ]
