# Generated by Django 6.0.5 on 2026-06-30 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_order_orderitem_product_productcategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='selected_options',
            field=models.CharField(blank=True, default='', help_text='e.g. "Hair Texture: Kinky Curly, Hair Length: 16in"', max_length=300),
        ),
        migrations.CreateModel(
            name='ProductOptionGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. "Hair Texture" or "Hair Length"', max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='option_groups', to='shop.product')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProductOptionValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('price_delta', models.DecimalField(decimal_places=2, default=0, help_text='Added to (or subtracted from) the base price when this is selected. Leave 0 if price does not change.', max_digits=8)),
                ('order', models.PositiveIntegerField(default=0)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='shop.productoptiongroup')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='shop/gallery/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='shop.product')),
                ('option_value', models.ForeignKey(blank=True, help_text='Optional — show this photo automatically when this option is selected', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='shop.productoptionvalue')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
